# Generated by Django 4.0.4 on 2022-04-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_isoverdued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadLine',
            new_name='deadline',
        ),
    ]
