# Generated by Django 4.0.4 on 2022-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_deadline_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='doneAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
